[project]
name = "HighwayHub"
version = "0.0.1"
description = "Highway Hub - software for car data aquisition and display"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "requests>=2.32.5",
    "nicegui>=3.10.0,<3.15.0",
    "numpy>=2.4.6",
    "pyserial>=3.5",
    "colorlog>=6.10.1",
    "pynmea2>=1.19.0"
]

[dependency-groups]
dev = [

]
